In [1]:
import numpy as np
import random
import operator
import math
import matplotlib.pyplot as plt 
from scipy.stats import multivariate_normal 
import cv2

In [31]:
image = cv2.imread('images/cars.jpg')

#number of data
n = image.shape[0] * image.shape[1]

#number of clusters
k = 6

#dimension of cluster
d = 5

# m parameter
m = 2

#number of iterations
MAX_ITERS = 12

print(image.shape)

(175, 287, 3)


In [3]:
def initializeMembershipWeights():

    weight = np.random.dirichlet(np.ones(k),n)
    weight_arr = np.array(weight)
    return weight_arr

In [4]:
#print(initializeMembershipWeights())
weight_arr = initializeMembershipWeights()
print(weight_arr)

[[0.23837205 0.34567403 0.41595392]
 [0.48974601 0.19570998 0.31454401]
 [0.38681595 0.14243526 0.47074878]
 ...
 [0.10096892 0.45379169 0.44523939]
 [0.16917248 0.2616512  0.56917632]
 [0.92357566 0.00869035 0.06773398]]


In [5]:
a1 = np.asarray([[1,2,3],[1,2,3]])
a2 = np.asarray([2,2])
#print(a1.shape)
#print(a2.shape)
#print(a2.dot(a1))
#print((a1.T / a2).T)
print(a1.sum(axis = 0))

[2 4 6]


In [6]:
def updateCentroids(weight_arr,data):
    Wij_power_m = np.power(weight_arr,m) 
    term1 = data.T.dot(Wij_power_m).T
    term2 = Wij_power_m.sum(axis = 0)
    V = (term1.T / term2).T  
    return V     

In [7]:
arr1 = np.asarray([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
#print(arr1.shape)
arr2 = np.asarray([2,2,1,1])
#print(arr2.shape)

arr3 = arr2 - arr1
#print(arr3.shape)
#print(np.sum(arr3, axis=0).shape)
print(np.identity(5, dtype = None))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
def updateDistances(V,A, data):
    
    clusters = V.shape[0]
    samples = data.shape[0]
        
    dist = np.zeros((samples, clusters))
    
    for i in range(0, clusters):
        for j in range(0,samples):
            dist_L1 = data[j,:] - V[i]
            #print(df.iloc[j,:].values)
            dist_L2 = dist_L1.T.dot(dist_L1.dot(A))
            dist[j,i] = np.sqrt(dist_L2)

    return dist
        

def updateWeightsv2(weight_arr,V,dist, data):
    
    clusters = V.shape[0]
    samples = data.shape[0]
    
    U = np.zeros((weight_arr.shape[0], weight_arr.shape[1]))

    for i in range(0, clusters):
        for j in range(0,samples):
            term = 0
            for k in range(0, clusters):
                term += np.power(np.divide(dist[j,i],dist[j,k]),2/(m-1))
            U[j,i] = np.divide(1, term)
            
    return U    

In [9]:
def FuzzyMeansAlgorithm(data):
    weight_arr = initializeMembershipWeights()
    for z in range(MAX_ITERS):
        C = updateCentroids(weight_arr, data)
        A = np.identity(d, dtype = None)
        dist = updateDistances(C,A, data)
        u = updateWeightsv2(weight_arr,C,dist, data)
        weight_arr = u
    return (weight_arr,C)

In [10]:
# c-mean clustering for image segmentation
data = np.zeros((10,5,3))
print(data.shape)
for i in range(0,data.shape[0]):
    data[i] = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
    

print(data)

(10, 5, 3)
[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]

 [[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]
  [13. 14. 15.]]]


In [11]:
def vectorize(image):
    
    data = np.zeros((image.shape[0] * image.shape[1],5))
    
    for i in range(0, image.shape[0]):
        for j in range(0, image.shape[1]):
            data[i * image.shape[1] + j] = np.array([image[i][j][0],image[i][j][1],image[i][j][2], i * 0.1, j * 0.1])
    
    return data

In [12]:
print(vectorize(image))


[[7.00e+01 7.70e+01 9.40e+01 0.00e+00 0.00e+00]
 [6.80e+01 7.30e+01 8.80e+01 0.00e+00 1.00e-01]
 [1.01e+02 1.03e+02 1.14e+02 0.00e+00 2.00e-01]
 ...
 [1.82e+02 1.90e+02 2.07e+02 1.93e+01 2.56e+01]
 [1.82e+02 1.90e+02 2.07e+02 1.93e+01 2.57e+01]
 [1.82e+02 1.90e+02 2.07e+02 1.93e+01 2.58e+01]]


In [13]:
def argmax(arr):
    l = []
    for i in range(0, arr.shape[0]):
        l.append(list(np.where(arr[i] == np.amax(arr[i]))[0])[0])
    return l

In [14]:
print(argmax(np.array([[1,2,12,13,4,5],[1,4,4,3,1,0],[1,2,12,13,40,5],[1,4,40,3,10,0]])))

[3, 1, 4, 2]


In [15]:
def generate_color(centeroid_number):
    colors = np.zeros((centeroid_number, 3))
    for i in range(0, centeroid_number):
        colors[i] = np.array([random.randint(0, 255) for _ in range(3)])
    return colors

In [16]:
print(generate_color(5))

[[124. 107. 253.]
 [242. 187. 216.]
 [ 37. 199.  80.]
 [ 54. 176.  17.]
 [ 30.  29.  97.]]


In [17]:
def devectorize(colors, pixel_segments, image):
    
    w = image.shape[1]
    h = image.shape[0]
    
    segmented_image = np.zeros((h, w, 3))
    for i in range(0, h):
        segmented_image[i] = np.array([colors[p] for p in pixel_segments[i * w: i * w + w]])
    return segmented_image

In [18]:
colors = np.array([[132. ,221.  ,11.],[ 67. ,224. ,210.],[234. ,154. ,199.]])
pixel_segments = [0,1,2,1,0,2]
imagev2 = np.zeros((2,3))

print(devectorize(colors, pixel_segments, imagev2).shape)

(2, 3, 3)


In [19]:
def segmentation(image):
    data = vectorize(image)
    final_weights,Centers = FuzzyMeansAlgorithm(data)
    pixel_segments = argmax(final_weights)
    colors = generate_color(k)
    segmented_image = devectorize(colors, pixel_segments, image)
    return segmented_image

In [32]:
segmented_image = segmentation(image)

In [33]:
cv2.imwrite('resualt.jpg',segmented_image)

True